# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.0
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --no-deps -r requirements-lock.txt -c requirements.txt
        # This should detect if the locked requirements are stale
    - name: Check lockfile covers requirements
      run: |
        ! join -v 1 <(grep -ioE '^([A-Z0-9]|[A-Z0-9][A-Z0-9._-]*[A-Z0-9])' requirements.txt | sort) \
                    <(grep -ioE '^([A-Z0-9]|[A-Z0-9][A-Z0-9._-]*[A-Z0-9])' requirements-lock.txt | sort) |
        grep .
    - name: Check environment is sane
      run: python -m pip check
    - name: Lint with flake8
      run: |
        python -m flake8
    - name: Test with pytest
      run: |
        python -m pytest
    - name: Test with mypy
      run: |
        python -m mypy .
